# Change these first
owner: pageon # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Pageon
    url: https://www.pageon.be
  - name: Kind van God
    url: https://blog.kindvangod.be
  - name: Carakas
    url: https://poetry.carakas.be
  - name: Arise
    url: https://arisefotografie.be
  - name: De bock verschooris
    url: http://debockverschooris.be
  - name: Caros
    url: http://carosbeauty.be
  - name: Train me
    url: http://train-me.be
  - name: evadoc
    url: http://evadoc.be
  - name: Every Nation Campus Gent
    url: http://everynationcampusgent.org
  - name: School of intersession
    url: https://www.schoolofintercession.eu
  - name: Go internship
    url: https://go-internship.eu
  - name: Add your voice today
    url: https://addyourvoicetoday.com
  - name: Add upir voice
    url: https://addyourvoice.today
  - name: Every Nation Lisboa
    url: https://everynationlisboa.org
  - name: Ik geloof in Tielt
    url: https://ikgeloofintielt.be
  - name: Naamcirkels
    url: https://naamcirkels.be
  - name: Feniks
    url: https://feniksateljee.be
  - name: Percecution
    url: https://www.persecution.be
  - name: Vervolging
    url: https://www.vervolging.be
  - name: Stagepro
    url: http://stagepro.be
  - name: mtcspoor6
    url: http://mtcspoor6.be
  - name: Masterhouse
    url: https://masterhouse.be
  - name: Norbert Roose
    url: http://norbertroose.be
  - name: Ik geloof in vlaanderen
    url: https://ikgeloofinvlaanderen.be
  - name: Grandes nouvelles
    url: https://grandesnouvelles.be
  - name: Educando
    url: http://educando.be
  - name: Connaitre Dieu
    url: https://connaitredieu.com
  - name: XEE
    url: https://xee.works
  - name: Feet up
    url: https://feet-up.be
  - name: Dock 66
    url: https://dock66.be
  - name: VEG
    url: https://veg.be
  - name: Open deur vzw
    url: http://opendeurvzw.be
  - name: Fantastic wheels
    url: https://fantasticwheels.be
  - name: Dreambaits
    url: https://www.dreambaits.be/en
  - name: De kruispoort
    url: https://dekruispoort.be/nl
  - name: Bijbeldag
    url: https://bijbeldag.be
assignees: # Users to assign downtime issues (optional)
  - Carakas
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.pageon.be
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pageon Uptime
  introTitle: "Pageon server uptime"
  introMessage: "Check our uptime here"
  navbar:
    - title: Status
      href: /
    - title: Pageon
      href: https://pageon.be

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
